GPU: [0,1,2,3]
VERBOSE: True
THREADS: 8  
SEED: 4567  

MODEL:
  MODE: 'Deraining'
  SESSION: 'ZWZNet'

OPTIM:
  BATCH_SIZE: 8
  NUM_EPOCHS: 500 
  TRAIN_EPOCH_SIZE: 10 
  VALID_EPOCH_SIZE: 2  
  EPOCH_MAX: 50  
  LR_INITIAL: 2e-4
  LR_MIN: 1e-6
  ALPHA: 50.0  
  W_ST: 0.0  
  W_LT: 0.0  
  BLOCKS: 5 
  NORM: IN 

DATASET:
  DATA_DIR: './datasets'  
  LIST_DIR: './file_list'  
  CROP_SIZE: 128  
  GEOMETRY_AUG: 0  
  ORDER_AUG: 0  
  SCALE_MIN: 0.5  
  SCALE_MAX: 2.0  
  SAMPLE_FRAMES: 5  
  
TRAINING:
  VAL_AFTER_EVERY: 5 
  RESUME: False
  TRAIN_PS: 256
  VAL_PS: 128
  SAVE_DIR: './checkpoints'          
